var path = require('path');
var merge = require("webpack-merge")
// Load the config generated by scalajs-bundler
var config = require('./scalajs.webpack.config');

var ResourcesDir = '../../../../src/main/resources'
var HtmlWebpackPlugin = require('html-webpack-plugin');
var CopyWebpackPlugin = require('copy-webpack-plugin');

module.exports = merge(config, {
  plugins: [
    new CopyWebpackPlugin([
      {
        from: 'node_modules/monaco-editor/min/vs',
        to: 'vs',
      }
    ]),
    new HtmlWebpackPlugin({
      inject: true,
      favicon: ResourcesDir + '/images/favicon.png',
      template: ResourcesDir + '/index.html',
      minify: {
        collapseWhitespace: true
      }
    })
  ]
});
